main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('info/',views.info, name='info'),
]

site_sushi/urls.py
from django.contrib import admin
from django.urls import path,include

from site_sushi import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('sushi.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('baskets.urls', namespace='basket')),
    path('customs/',include('customs.urls',namespace='customs'))


]

if settings.DEBUG:
    urlpatterns += [ path("__debug__/", include("debug_toolbar.urls")), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sushi/urls.py
from django.urls import path

from sushi import views

app_name = 'sushi'

urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('<slug:category_slug>/',views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),

]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('registration/',views.registration, name='registration'),
    path('profile/',views.profile, name='profile'),
    path('users_basket/',views.users_basket, name='users_basket'),
    path('logout/',views.logout, name='logout'),
]

customs/models.py
from django.db import models
from sushi.models import Products

from users.models import User


class CustomitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Custom(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Користувач",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення замовлення")
    phone_number = models.CharField(max_length=10, verbose_name="Номер телефону")
    requires_delivery = models.BooleanField(default=False, verbose_name="Доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адреса доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при отриманні ")
    is_paid = models.BooleanField(default=False, verbose_name="Сплачено")
    status = models.CharField(max_length=50, default='Опрацювується', verbose_name="Статус замовлення")

    class Meta:
        db_table = "custom"
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлень"

    def __str__(self):
        return f"Замовлення № {self.pk} | Одержувач {self.user.first_name} {self.user.last_name}"


class CustomItem(models.Model):
    custom = models.ForeignKey(to=Custom, on_delete=models.CASCADE, verbose_name="Замовлення")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажу")

    class Meta:
        db_table = "custom_item"
        verbose_name = "Продане замовлення"
        verbose_name_plural = "Продані замовлення"

    objects = CustomitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Продукт {self.name} | Замовлення № {self.custom.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images',blank=True,null=True, verbose_name='Фотографія')
    phone_number = models.CharField(max_length=11,blank=True,null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Користувача'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"

        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email"
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.shortcuts import render
from django.contrib import auth,messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch

from users.forms import UserLoginForm
from users.forms import UserRegistrationForm
from users.forms import ProfileForm
from baskets.models import Basket
from customs.models import Custom, CustomItem

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username,password=password)
            if user:
                auth.login(request,user)
                messages.success(request,f"{username}, Ви успішно ввійшли до свого аккаунту")
                direct_page = request.POST.get('next', None)
                if direct_page and direct_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Акамедзутсу - Авторизація',
        'form': form
    }
    return render(request,'users/login.html',context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request,user)
            messages.success(request, f"{user.username}, Ви успішно зареєструвались і увійшли до свого аккаунту")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Акамедзутсу - Регістрація',
        'form': form
    }
    return render(request,'users/registration.html',context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST,instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Ви успішно оновили свій профіль")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

        customs = Custom.objects.filter(user=request.user).prefetch_related(
            Prefetch(
                "customitem_set",
                queryset=CustomItem.objects.select_related("product"),
            )
        ).order_by("-id")

    context = {
        'title': 'Акамедзутсу - Особистий кабінет',
        'form': form,
        'customs' : customs
    }
    return render(request,'users/profile.html',context)

def users_basket(request):
    return render(request,'users/users_basket.html')



@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Ви успішно вийшли із свого аккаунту")
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Авторизація</h2>
                                    <form action="{% url "user:login" %}" method="post" >
                                        {% csrf_token %}
                                        {% if request.GET.next %}
                                            <input type="hidden" name="next" value={{ request.GET.next }}>
                                        {% endif %}
                                        <div class="mb-3">
                                            <label for="id_username" class="form-label">Ім'я користувача</label>
                                            <input type="text" class="form-control" value="{% if form.username.value%}{{form.username.value}}{% endif %}" name="username" id="id_username" placeholder="Введіть ім'я користувача" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="id_password" class="form-label">Пароль</label>
                                            <input type="password" class="form-control" name="password" id="id_password" placeholder="Введіть ваш пароль" required>
                                        </div>

                                        <button type="submit" class="btn btn-success btn-block">Вхід</button>
                                    </form>
                                    <div class="mt-3">
                                         <a href="{% url "user:registration" %}">Створити аккаунт</a>
                                    </div>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load baskets_tags %}
{% block content %}>
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профіль користувача</h3>
                                        <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                                             {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12 mb-3 text-center">
                                                    {% if user.image %}
                                                        <img src="{{ user.image.url }}"
                                                        alt="Ваш аватар" class="img-fluid rounded-circle"
                                                        style="max-width: 150px;">
                                                    {% else %}
                                                    {% endif %}
                                                    <input type="file" class="form-control mt-3" id="id_image"
                                                           name="image"
                                                        accept="image/*">
                                                        {% if form.image.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_first_name" class="form-label">Ім'я*</label>
                                                    <input type="text" class="form-control" id="id_first_name"
                                                           name="first_name"
                                                        placeholder="Введіть ваше ім'я"
                                                           value="{{ form.first_name.value }}" required>
                                                        {% if form.first_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_last_name" class="form-label">Прізвище*</label>
                                                    <input type="text" class="form-control" id="id_last_name"
                                                           name="last_name"
                                                        placeholder="Введіть ваше прізвище"
                                                           value="{{ form.last_name.value }}" required>
                                                        {% if form.last_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_username" class="form-label">Ім'я користувача*</label>
                                                    <input type="text" class="form-control" id="id_username"
                                                           name="username"
                                                        placeholder="Введіть ім'я користувача"
                                                           value="{{ form.username.value }}" required>
                                                        {% if form.username.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_email" class="form-label">Email*</label>
                                                    <input type="email" class="form-control" id="id_email"
                                                           name="email"
                                                        placeholder="Введіть ваш email"
                                                           value="{{ form.email.value }}" required>
                                                        {% if form.email.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                                        {% endif %}
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-success">Зберегти</button>
                                        </form>
                                    </div>
                                </div>
                                {% user_baskets request as baskets %}
                            
                                <div class="col-md-7">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Корзина</h3>
                                        <div class="container" id="cart-items-container">
                                            {% include "baskets/includes/included_basket.html" %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Мої замовлення</h3>
                                        <div class="container">
                                            <div class="accordion" id="accordionExample">
                                                    {% for custom in customs %}
                                                    <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading1">
                                                        <button class="accordion-button btn-success" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                                            Заказ № {{ custom.id }} - {{ custom.created_timestamp }} | Статус:<strong class="mx-2"> В обробці {% comment %}{{ custom.requires_delivery }}{% endcomment %}</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse1{{ custom.id }}" class="accordion-collapse collapse {% if custom == customs.0 %}show{% endif %}"  aria-labelledby="heading{{ custom.id }}" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-success table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Продукт</th>
                                                                        <th>Кількість</th>
                                                                        <th>Ціна</th>
                                                                        <th>Загальна вартість</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    {% for item in custom.customitem_set.all %}
                                                                    <tr>
                                                                        <td><a class="text-dark" href="{% url "sushi:product" item.product.slug %}">{{ item.product.name }}</a></td>
                                                                        <td>{{ item.quantity }}</td>
                                                                        <td> {{ item.price }} грн</td>
                                                                        <td>{{ item.products_price }} грн</td>

                                                                    </tr>
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}

                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Реестрація</h2>
                                    <form action="{% url "user:registration" %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Ім'я*</label>
                                                <input type="text" class="form-control" id="id_first_name"
                                                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" name="first_name"
                                                    placeholder="Введіть ваше ім'я" required>
                                                    {% if form.first_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Прізвище*</label>
                                                <input type="text" class="form-control" id="id_last_name"
                                                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" name="last_name"
                                                    placeholder="Введіть ваше прізвище" required>
                                                    {% if form.last_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_username" class="form-label">Ім'я користувача*</label>
                                                <input type="text" class="form-control" id="id_username"
                                                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}" name="username"
                                                    placeholder="Введіть ім'я користувача" required>
                                                    {% if form.username.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_email" class="form-label">Email*</label>
                                                <input type="email" class="form-control" id="id_email"
                                                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}" name="email"
                                                    placeholder="Введіть email адресу" required>
                                                    {% if form.email.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_password1" class="form-label">Пароль*</label>
                                                <input type="password" class="form-control" id="id_password1"
                                                       value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}" name="password1"
                                                    placeholder="Створіть пароль" required>
                                                    {% if form.password1.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_password2" class="form-label">Підтвердіть пароль*</label>
                                                <input type="password" class="form-control" id="id_password2"
                                                       value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}" name="password2"
                                                    placeholder="Підтвердіть пароль" required>
                                                    {% if form.password2.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                                    {% endif %}
                                            </div>
                                        </div>
                                        <button type="submit"
                                            class="btn btn-success btn-block">Зареєструвати</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

users/templates/users/users_basket.html
{% extends "base.html" %}
{% load static %}
{% load baskets_tags %}

{% block content %}
    {% user_baskets request as baskets %}
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                    <h3 class="text-center mb-4">Корзина</h3>
                                    <div class="container" id="cart-items-container">
                                        {% include "baskets/includes/included_basket.html" %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}