customs/urls.py
from django.urls import path

from customs import views

app_name = 'customs'

urlpatterns = [
    path('create-custom/',views.create_customs, name = 'create_customs'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('info/',views.info, name='info'),
]

site_sushi/urls.py
from django.contrib import admin
from django.urls import path,include

from site_sushi import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('sushi.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('baskets.urls', namespace='basket')),
    path('customs/',include('customs.urls',namespace='customs'))


]

if settings.DEBUG:
    urlpatterns += [ path("__debug__/", include("debug_toolbar.urls")), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sushi/urls.py
from django.urls import path

from sushi import views

app_name = 'sushi'

urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('<slug:category_slug>/',views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),

]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('registration/',views.registration, name='registration'),
    path('profile/',views.profile, name='profile'),
    path('users_basket/',views.users_basket, name='users_basket'),
    path('logout/',views.logout, name='logout'),
]

templates/base.html
{% load static %}
{% load sushi_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    {% block css %} {% endblock  %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-success" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand bg-mybutton" href="{% url "main:index" %} ">Головна сторінка</a>
                <button class="navbar-toggler bg-mybutton bg-gradient " type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse "  id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Інформація
                            </a>
                            <ul class="dropdown-menu bg-success bg-gradient">
                                <li><a class="dropdown-item  text-white" href="{% url "customs:create_customs" %}">Доставка і оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:info" %}">Наші контакти</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">О нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "users:users_basket" %}">Корзина</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:login" %}">Вхід</a>
                        </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                     Мій профіль
                                </a>
                            <ul class="dropdown-menu bg-success bg-gradient">
                                <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Особистий кабінет</a>
                                </li>
                                {% if user.is_admin or user.is_staff %}
                                    <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Адмін панель</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Вихід</a></li>
                            </ul>
                        </li>
                        {% endif %}

                    </ul>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2 bg-body-secondary" type="search" name="q" placeholder="Пошук" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Пошук продуктів</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <div class="row mt-1 position-fixed z-3 ">
                <div class="dropdown mb-2 ">
                    <button class="btn btn-secondary dropdown-toggle btn-success" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                             height="16">
                    </button>
                    <ul class="dropdown-menu bg-success bg-gradient" data-bs-theme="dark">

                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white " href="{% url "catalog:index" category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                </div>
                {% block modal_basket %}{% endblock %}
            </div>
        </div>
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-9">
                    {% include "includes/notifications.html" %}
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %} {% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>