baskets/urls.py
from django.urls import path

from baskets import views

app_name = 'baskets'

urlpatterns = [
    path('basket_add/<slug:product_slug>/',views.basket_add, name='basket_add'),
    path('basket_change/',views.basket_change, name='basket_change'),
    path('basket_remove/<int:basket_id>/',views.basket_remove, name='basket_remove'),

]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('info/',views.info, name='info'),
]

site_sushi/urls.py
from django.contrib import admin
from django.urls import path,include

from site_sushi import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('sushi.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('baskets.urls', namespace='basket')),
    path('customs/',include('customs.urls',namespace='customs'))


]

if settings.DEBUG:
    urlpatterns += [ path("__debug__/", include("debug_toolbar.urls")), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sushi/urls.py
from django.urls import path

from sushi import views

app_name = 'sushi'

urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('<slug:category_slug>/',views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),

]

sushi/models.py
from django.db import models
from django.urls import reverse

class Categories(models.Model):
    name = models.CharField(max_length=150,unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200,unique=True,blank = True,null = True, verbose_name = 'URL')
    class Meta:
        db_table = 'category'
        verbose_name = 'Категорію'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank = True, null = True, verbose_name= 'Опис')
    image = models.ImageField(upload_to= "sushi_images", blank=True, null=True,verbose_name='Зображення')
    price = models.DecimalField(default=0.00,max_digits=10, decimal_places=2,verbose_name='Ціна')
    discount = models.DecimalField(default=0.00,max_digits=4, decimal_places=2,verbose_name='Знижка в відсотках')
    quantity = models.PositiveIntegerField(default=0,verbose_name='Кількість')
    category = models.ForeignKey(to=Categories,on_delete=models.CASCADE, verbose_name='Категорія')
    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукти'
        ordering = ("id",)

    def __str__(self):
        return f'{self.name} Кількість - {self.quantity}'

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs ={"product_slug": self.slug})

    def product_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100,2)

        return self.price

sushi/views.py
from django.shortcuts import render
from django.shortcuts import get_list_or_404
from django.core.paginator import Paginator
from sushi.models import Products
from sushi.utils import q_search

def catalog(request,category_slug=None):

    page = request.GET.get('page',1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q',None)


    if category_slug == "all":
        sushi = Products.objects.all()

    elif query:
        sushi = q_search(query)

    else:
        sushi = Products.objects.filter(category__slug=category_slug)

    if on_sale:
        sushi = sushi.filter(discount__gt=0)

    if order_by and order_by != "default":
        sushi = sushi.order_by(order_by)

    paginator = Paginator(sushi,3)
    page = paginator.page(int(page))

    context = {
        'title': 'Акамедзутсу - Каталог',
        'goods': page,
        'slug_url': category_slug,
    }
    return render(request, 'sushi/catalog.html', context)

def product(request,product_slug):

    product = Products.objects.get(slug=product_slug)

    context = {
        "product": product
    }

    return render(request, 'sushi/product.html',context=context)

sushi/templates/sushi/catalog.html
{% extends "base.html" %}
{% load static %}
{% load sushi_tags %}

{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}
<div class="row">
                        <!-- Форма фільтрів -->
                        <div class="dropdown mb-2">
                            <button class="btn btn-secondary dropdown-toggle btn-success" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Фільтр
                            </button>

                            <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get"
                                  class="dropdown-menu bg-success bg-gradient" data-bs-theme="dark">
                                <div class="form-check text-white mx-3">
                                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %} checked {% endif %}>
                                    {% if request.GET.q %}
                                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                                    {% endif %}
                                    <label class="form-check-label" for="flexCheckDefault">
                                        Акційні пропозиції
                                    </label>
                                </div>
                                <p class="text-white mx-3 mt-3">Сортировать:</p>
                                <div class="form-check text-white mx-3">
                                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                                    {% if not request.GET.order_by or request.GET.order_by == 'default' %} checked {% endif %}>
                                    <label class="form-check-label" for="flexRadioDefault1">
                                        За замовчуванням
                                    </label>
                                </div>
                                <div class="form-check text-white mx-3">
                                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                                            {% if request.GET.order_by == 'price' %} checked {% endif %}>
                                    <label class="form-check-label" for="flexRadioDefault2">
                                        Від дешевих до дорогих
                                    </label>
                                </div>
                                <div class="form-check text-white mx-3">
                                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                                            {% if request.GET.order_by == '-price' %} checked {% endif %}>
                                    <label class="form-check-label" for="flexRadioDefault3">
                                        Від дорогих до дешевих
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-light mx-3 mt-3">Застосувати</button>
                            </form>
                        </div>

                        {% if resuqest.GET.q %}
                        <h3 class="mt-4">Результати пошуку {{ request.GET.q }}</h3>
                            <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
                        {% if not goods %}
                            <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
                            <h2 class="mt-4">Результати пошуку нічого не виявили</h2>
                        {% endif %}
                        {% endif %}
                        {% for product in goods  %}
                        <!-- Карта товару -->
                        <div class="col-lg-4 col-md-6 p-4">
                            <div class="card rounded custom-shadow">
                                {% if product.image %}
                                    <img src="{{product.image.url }}" class="card-img-top" alt="{{product.name }}">
                                {% else %}
                                    <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <a href="{% url "catalog:product" product.slug %}">
                                        <p class="card-title">{% autoescape off %}{% if product.headline %}{{ product.headline }}{% else %}{{ product.name }}{% endif %}{% endautoescape %}</p>
                                    </a>
                                    <p class="card-text">{% autoescape off %}{% if product.bodyline %}{{ product.bodyline|truncatechars:175 }}{% else %}{{ product.description|truncatechars:31}}{% endif %}{% endautoescape %}</p>
                                    <p class="product_id">id: {{ product.product_id }}</p>
                                    <div class="d-flex justify-content-between">

                                        {% if product.discount %}
                                            <p><s>{{ product.price }}</s> грн</p>
                                            <p><strong>{{ product.sell_price }} грн</strong></p>
                                            <span class="badge bg-warning text-dark">{{ product.discount }} %</span>
                                        {% else %}
                                            <p><strong>{{ product.price }} грн</strong></p>
                                        {% endif %}

                                        <a href="{% url "basket:basket_add" product.slug %}" class="btn add-to-cart">
                                            <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                                width="32" height="32">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
<!-- Пагінація -->
    {% if goods %}
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
<nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center my-4">
                            <div class="custom-shadow d-flex">
                                <li class="page-item {% if not goods.has_previous %} disabled{% endif %}">
                                  <a class="page-link" href="{% if goods.has_previous %}?{% change_params page1=goods.previous_page_number %}{% else %}#{% endif %}" >Назад</a>
                                </li>

                                {% for page1 in goods.paginator.page_range %}
                                    {% if page1 >= goods.number|add:-3 and page1 <= goods.number|add:+3 %}
                                        <li class="page-item{% if goods.number == page1 %} active {% endif %}">
                                            <a class="page-link" href="?{% change_params page=page1 %}">{{ page1 }}</a>
                                       </li>
                                    {% endif %}
                                {% endfor %}

                                <li class="page-item {% if not goods.has_next %} disabled{% endif %}">
                                  <a class="page-link" href="{% if goods.has_next %}?{% change_params page1=goods.next_page_number %}{% else %}#{% endif %}" >Вперед</a>
                                </li>
                            </div>
                        </ul>
                    </nav>
    {% endif %}
{% endblock %}














{% block footer %}
<footer class="py-4 bg-success">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Cursova Dyachenko Daniil 2024</p>
    </div>
</footer>
{% endblock %}

sushi/templates/sushi/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}
<div class="container mt-5">
                        <div class="card mb-4 custom-shadow d-flex ">
                            <div class="row">
                                <!-- Мініатюри -->
                                <div class="col-md-4">
                                    <img src="{{ product.image.url }}"
                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                                </div>
                                <div class="col-md-8 mt-5 ">
                                    <h5 class="card-title text-center">{{ product.name }}</h5>
                                    <p class="card-text text-center">{{ product.description }}</p>
                                </div>
                                <!-- Збільшити зображення у модальному вікні -->
                                <div class="modal fade" id="imageModal1" tabindex="-1"
                                    aria-labelledby="imageModal1Label" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Закрыть"></button>
                                            </div>
                                            <div class="modal-body">
                                                <img src="{{ product.image.url }}"
                                                    class="img-fluid" alt="Изображение 1">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Опис товару -->
                            <div class="card-body">
                                <p class="product_id mb-0">id: {{ product.product_id }}</p>
                                <p class="card-text ">Ціна: <strong>{{ product.sell_price}} грн</strong> </p>
                                <a href="{% url "basket:basket_add" product.slug %}" class="btn btn-dark add-to-cart">Додати до кошику продуктів</a>
                            </div>
                        </div>
                    </div>
{% endblock %}