customs/urls.py
from django.urls import path

from customs import views

app_name = 'customs'

urlpatterns = [
    path('create-custom/',views.create_customs, name = 'create_customs'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('info/',views.info, name='info'),
]

site_sushi/urls.py
from django.contrib import admin
from django.urls import path,include

from site_sushi import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('sushi.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('baskets.urls', namespace='basket')),
    path('customs/',include('customs.urls',namespace='customs'))


]

if settings.DEBUG:
    urlpatterns += [ path("__debug__/", include("debug_toolbar.urls")), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customs/models.py
from django.db import models
from sushi.models import Products

from users.models import User


class CustomitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Custom(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Користувач",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення замовлення")
    phone_number = models.CharField(max_length=10, verbose_name="Номер телефону")
    requires_delivery = models.BooleanField(default=False, verbose_name="Доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адреса доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при отриманні ")
    is_paid = models.BooleanField(default=False, verbose_name="Сплачено")
    status = models.CharField(max_length=50, default='Опрацювується', verbose_name="Статус замовлення")

    class Meta:
        db_table = "custom"
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлень"

    def __str__(self):
        return f"Замовлення № {self.pk} | Одержувач {self.user.first_name} {self.user.last_name}"


class CustomItem(models.Model):
    custom = models.ForeignKey(to=Custom, on_delete=models.CASCADE, verbose_name="Замовлення")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажу")

    class Meta:
        db_table = "custom_item"
        verbose_name = "Продане замовлення"
        verbose_name_plural = "Продані замовлення"

    objects = CustomitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Продукт {self.name} | Замовлення № {self.custom.pk}"

customs/forms.py
import re
from django import forms


class CreateCustomForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ],
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
        ],
    )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("У вашому номері телефона є букви? Введіть тільки цифри")

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Невірний формат номеру")

        return data

customs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect

from baskets.models import Basket

from customs.forms import CreateCustomForm
from customs.models import Custom, CustomItem

@login_required
def create_customs(request):
    if request.method == 'POST':
        form = CreateCustomForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    basket_items = Basket.objects.filter(user=user)

                    if basket_items.exists():
                        custom = Custom.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        for basket_item in basket_items:
                            product = basket_item.product
                            name = basket_item.product.name
                            price = basket_item.product.sell_price()
                            quantity = basket_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Таких продуктів на данний момент немає {name} \
                                                           В наявності - {product.quantity}')

                            CustomItem.objects.create(
                                custom=custom,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        basket_items.delete()

                        messages.success(request, 'Замовлення прийнято!')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('basket:custom')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }

        form = CreateCustomForm(initial=initial)

    context = {
        'title': 'Акамедзутсу - Оформлення замовлення',
        'form': form,
        'custom': True,
    }
    return render(request, 'customs/create_custom.html', context=context)

customs/templates/customs/create_custom.html
{% extends 'base.html' %}
{% load static %}
{% load baskets_tags %}

{% block content %}
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <div class="container">
                            <h3 class="text-center mb-4">Ваші товари</h3>
                            <div class="container" id="cart-items-container">
                                {% user_baskets request as baskets %}
                                {% include 'baskets/includes/included_basket.html' %}
                            </div>
                        </div>
                        <div class="container">
                            <h3 class="text-center">Деталі замовлення</h3>
                            <div class="card mb-3">
                                <div class="card-body">
                                    <form action="{% url "customs:create_customs" %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Ваше ім'я:</label>
                                                <input type="text" class="form-control" id="id_first_name"
                                                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                                    name="first_name" required>
                                                    {% if form.first_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Ваше прізвище:</label>
                                                <input type="text" class="form-control" id="id_last_name" name="last_name"
                                                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                                       required>
                                                        {% if form.last_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                                        {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_phone_number" class="form-label">Ваш номер телефону:</label>
                                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                                       value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                                    placeholder="Формат: 0XXXXXXXXX"
                                                    required>
                                                    {% if form.phone_number.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <label for="delivery" class="form-label">Спосіб доставки: </label>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="1" checked>
                                                    <label class="form-check-label" for="id_requires_delivery">Доставка
                                                    </label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="0">
                                                    <label class="form-check-label" for="id_requires_delivery">Самовивіз з бару</label>
                                                </div>
                                            </div>
                                            <div class="mb-3" id="deliveryAddressField">
                                                <label for="id_delivery_address" class="form-label">Ваша адреса
                                                    доставки:</label>
                                                <textarea class="form-control" id="id_delivery_address"
                                                          value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                                    name="delivery_address" rows="2"></textarea>
                                                    {% if form.delivery_address.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <label class="form-label">Спосіб оплати: </label>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="0" checked>
                                                    <label class="form-check-label" for="id_payment_on_get">Оплата онлайн
                                                    </label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="1">
                                                    <label class="form-check-label" for="id_payment_on_get">Оплата готівкою/картою при отриманні</label>
                                                    {% if form.paymant_on_get.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.payment_on_get.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-dark">Оформити замовлення</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}